### ISSUE TITLE
Submit the treeview to upstream Select2?

### ISSUE THREAD

**Issue by mestaritonttu** [maliming/select2-treeview#1]
First of all, thank you for this very requested solution! Would you consider submitting this to the Select2 project? There is this issue: https://github.com/select2/select2/issues/3269

**Comment by maliming** [comment]
hi @mestaritonttu 
i will try but Select2 is a big project, i do not know whether it can be a good combination.

**Comment by maliming** [comment]
[select2 pr ](https://github.com/select2/select2/pull/4717)

**Comment by BinWu1989** [comment]
Seems that the parent node could not be choosed ,right?

**Comment by maliming** [comment]
@BinWu1989 
In fact, the parent node is html of the optgroup.
Optgroup can not be selected.
